#!/usr/bin/env bash
# displays information about the specified subdomain

if (($# == 1)))
then
	subdomain=(www lb-01 web-01 web-02)
else
	subdomain=("$2")
fi

domain () {
		for m in "${subdomain[@]}"
		do
		record=$(dig $m.$1 | awk 'f{print $4;f=0} /;; ANSWER SECTION:/{f=1}')
		ip=$(dig $m.$1 | awk 'f{print $5;f=0} /;; ANSWER SECTION:/{f=1}')
		echo The subdomain $m is a $record record and points to $ip
		done
}
