#!/usr/bin/env bash
# Transfer file to server

if [ $# -ne 4 ];
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
else
  PATH_TO_FILE=$1
  IP=$2
  USERNAME=$3
  PATH_TO_SSH_KEY=$4

  scp -i $4 -o StrictHostKeyChecking=no $1 '$3@$2':~/
fi
