#!/usr/bin/env bash
# Transfer file to server

if [ $# -ne 4 ];
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
else
  PATH_TO_FILE=$1
  IP=$2
  USERNAME=$3
  PATH_TO_SSH_KEY=$4

  scp -o StrictHostKeyChecking=no "$path_to_ssh_key" "$path_to_file" "$username"@"$ip":~/
fi
