#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "/^\sserver_name.*/a \    rewrite ^/redirect_me(/*) https://www.youtube.com/watch?v=QH2-TGUlwu4 /etc/nginx/sites-available/default
sudo service nginx restart
