#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "/^\sserver_name.*/a \    rewrite ^/redirect_me(/*) https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "/^\slocation.*/i \        error_page 404 /404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
