#!/usr/bin/env bash
# Configure nginx for connection on port 80

# Remove the nginx configuration file
rm /etc/nginx/sites-enabled/default

# create link to inherit the current nginx features 
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart nginx
service nginx restart
