#!/usr/bin/env bash
# This script displays numbers from 1 to 100
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format
for m in {1..100}
do
	if [ $(( m % 15 )) = 0 ]
	then
		echo "FizzBuzz"
	elif [ $(( m % 3 )) = 0 ]
	then
		echo "Fizz"
	elif [ $(( m % 5 )) = 0 ]
	then
		echo "Buzz"
	else
		echo "$m"
	fi
done
