#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# and iterates 9th line by displaying "Best School" and
# then Hi

m=0
while [ "$m" -lt "10" ]
do
	echo "Best School"

	if [ "$m" -eq "8" ]
	then
		echo "Hi"
	fi
	m=$(( m + 1 ))
done
