#!/usr/bin/env bash
# This script is displaying "Best School" looping from 1-10
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

m=0
while [ $m -lt 10 ]
do
	if [ $m = 3 ]
	then
		echo "bad luck"
	elif [ $m = 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	m=$((m + 1))
done
