#!/usr/bin/env bash
# Script that configures NGINX and run as nginx user

# Update the listening ports
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default

# Change the terms on the config file
chmod 644 /etc/nginx/nginx.conf

# Kill the apache2 server
pkill apache2

# Restart nginx
sudo -u nginx service nginx start
