#!/usr/bin/env bash
# make task 1 script short and sweet
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
pkill -9 apache
sudo nginx -c "service nginx restart"
